### ISSUE TITLE
1.5.07 BALL_COUNT should be 0 at first

### ISSUE THREAD

**Issue by Gabriel-Bowater** [udacity/ud405#13]
The extension work has already been done in the base project meaning that the program renders 10000 balls right away. Needs to be set to 0 to just render a single ball for the initialize challenge, or rewritten to have no handling for multiple balls to leave it for students to figure out.

**Comment by xyclos** [comment]
the for loop should initialize i to be 1 rather than 0, so the BALL_COUNT can be the literal number of balls rather than the number of balls - 1;

**Comment by JeremySilverTongue** [comment]
Whoops. Fixed the ball counts to 1 for the exercise, and 10000 for the solution. As for the loop, you're talking about this one, right?

        for (int i = 0; i < BALL_COUNT; i++) {
            balls.add(new BouncingBall(viewport));
        }

I think this one behaves as you want it to, @xyclos, where BALL_COUNT is indeed the literal number. That look right to you? If not, please reopen. Thanks!
