### ISSUE TITLE
Bubble radius

### ISSUE THREAD

**Issue by alakdae** [udacity/ud405#20]
In the video you say the bubble should touch the outer line at 9.8, but this code does not account for bubble radius and the bubble center is on the line of outer circle at 9.8.

This code does account for the bubble radius:
        renderer.setColor(Color.RED);

        renderer.circle(WORLD_SIZE / 2, WORLD_SIZE / 2, WORLD_SIZE / 4, 64);

        // TODO: Draw a circle to indicate 9.8m/s^2

        renderer.setColor(Color.GREEN);

        // TODO: Draw a circle to hold the bubble when the phone is flat
        renderer.circle(WORLD_SIZE / 2, WORLD_SIZE / 2, WORLD_SIZE / 14, 64);

        renderer.set(ShapeType.Filled);

        // TODO: Draw the bubble
        renderer.circle(
                WORLD_SIZE / 2 - yAxis * WORLD_SIZE / (4f*9.8f) + yAxis / 9.8f / 4f * WORLD_SIZE / 4, 
                WORLD_SIZE / 2 + xAxis * WORLD_SIZE / (4f*9.8f) - xAxis / 9.8f / 4f * WORLD_SIZE / 4, 
                WORLD_SIZE/16, 
                64);

**Comment by JeremySilverTongue** [comment]
Very good point. Fixed!
