### ISSUE TITLE
1.3.02-Exercise-DrawAStarfield gives errors in Android Studio

### ISSUE THREAD

**Issue by jwill** [udacity/ud405#3]
Running desktop:run task gives errors Unsupported major.minor version 51.0 (Java 7)

<img width="868" alt="screen shot 2015-09-27 at 9 36 24 pm" src="https://cloud.githubusercontent.com/assets/66931/10127967/e19c17d2-655f-11e5-95bb-aec39e77ebf6.png">

It's because Robovm requires Java 1.7+. My Android Studio was using Java 6 JRE despite JAVA_HOME being set to 1.8. I fixed following the steps below to remove 1.6 from the plist file and force Android Studio to use Java 1.8:

http://www.gamefromscratch.com/post/2014/04/03/Troubleshooting-IntelliJLibGDXRoboVMGradle-issues-on-Mac-OS.aspx

An easier fix is removing the ios project from the gradle file.

I think it could be an issue that only affects versions of Android Studio that copied settings over from a previous install.

**Comment by JeremySilverTongue** [comment]
@louis-udacity Have any students reported having problems with Java versions?

**Comment by JeremySilverTongue** [comment]
My impression is that this issue def needs to be addressed if you want to build the iOS backend, but I think that in general the student should be fine. Not sure why this blew up for you. Gonna close for now, but if this starts coming up in the forums, we can definitely address.
