### ISSUE TITLE
About alternative recursion method

### ISSUE THREAD

**Issue by Kvaibhav01** [udacity/ud405#32]
The GitHub profile URL _https://github.com/khafan_ is no longer in existence in [DrawTheCantorGasket.java](https://github.com/udacity/ud405/blob/master/1.3.08-Solution-DrawTheCantorGasket/core/src/com/udacity/gamedev/drawthecantorgasket/DrawTheCantorGasket.java). You may remove the link from there only mentioning the username as _khafan_.

Line 83 of the file: https://github.com/udacity/ud405/blob/525fcd7ca269bb9c47ba6aaa557d8a659dea3e17/1.3.08-Solution-DrawTheCantorGasket/core/src/com/udacity/gamedev/drawthecantorgasket/DrawTheCantorGasket.java#L83

Also, I'm not able to understand this part of code where we use recursion as given by khafan user. This:

```
for (int i = 0; i < 9; i++) 
{
        if (i == 4) continue;
          punchCantorGasket(i%3 * newSize + x, i/3 * newSize + y, newSize, recursions);  
 }
```

**Comment by jwill** [comment]
Leaving as is...as there is currently a user named khafan and for historic code attribution reasons

As for the loop, I advise setting breakpoints and observing the values being set in that function.
