### ISSUE TITLE
Desktop run doesnt work?

### ISSUE THREAD

**Issue by macleodiain** [udacity/ud405#40]
I can run the app on my android device and on my desktop if i run from the command line using gradlew desktop:run but when i set up the run configuration i get the error message: " Could not create service of type BuildSessionScopeServices$CrossBuildFileHashCacheWrapper using BuildSessionScopeServices.createCrossBuildChecksumCache()."

**Comment by simro** [comment]
Hi macleodiain, how can you solved the problem?
