### ISSUE TITLE
Better algorithm for 1.3.08-Solution-DrawTheCantorGasket

### ISSUE THREAD

**Issue by khafan** [udacity/ud405#9]
I know it's not really important but Wouldn't it be better using these lines
```java
for (int i = 0; i < 9; i++) {
    if (i == 4) continue;
    punchCantorGasket(i%3 * size/3 + x, i/3 * size/3 + y, size/3, recursions - 1);
}
```
instead of below lines?
```java
float newSize = size/3;

punchCantorGasket(x, y, newSize, recursions - 1);
punchCantorGasket(x + newSize, y, newSize, recursions - 1);
punchCantorGasket(x + 2 * newSize, y, newSize, recursions-1);
punchCantorGasket(x, y + newSize, newSize, recursions-1);
punchCantorGasket(x + 2 * newSize, y + newSize, newSize, recursions - 1);
punchCantorGasket(x, y + 2 * newSize, newSize, recursions - 1);
punchCantorGasket(x + newSize, y + 2 * newSize, newSize, recursions-1);
punchCantorGasket(x + 2 * newSize, y + 2 * newSize, newSize, recursions - 1);
```      
Less verbosity and more readable.

**Comment by JeremySilverTongue** [comment]
Yeah yours is definitely the style I'd prefer, but I think for a more newbie programmer the unrolled loop might be easier to grok. Not sure. Mind if I put your code in the solution as well, as an example of another way to do it?

**Comment by khafan** [comment]
I would be glad if you do so, tnx

**Comment by JeremySilverTongue** [comment]
Added! Thanks :D

https://github.com/udacity/ud405/blob/6bc68d9f566de2a3f463a54ce67d9b6024a4a32b/1.3.08-Solution-DrawTheCantorGasket/core/src/com/udacity/gamedev/drawthecantorgasket/DrawTheCantorGasket.java#L71-L77
